### ISSUE TITLE
How to register onTimeout callback without Kdyby/Events?

### ISSUE THREAD

**Issue by lucien144** [Kdyby/RabbitMq#59]
This is not a bug, but help request.

What's the proper way to register `onTimeout` callback but without `Kdyby\Events`, please? I know that with `Kdyby\Events` it looks like this 👇  but I'm not sure how to do that without `Kdyby\Events`.

```
$consumer->onTimeout[] = function () {
    // do something
};
```

Also, when and where is the best time to register such event? I configure the connection with all consumers/producers using the `config.neon` and I don't feel right to do that in any presenter before call `$producer->publish();`.

Thanks.

**Comment by fprochazka** [comment]
Actually no, that is [just plain Nette](https://doc.nette.org/en/2.4/php-language-enhancements#toc-events). 

Kdyby/Events allows you to [write Listener classes](https://github.com/Kdyby/Events/blob/master/docs/en/index.md) and then bind them to the desired events easily.

If you wanna do it without, it's not exactly nice, but this should work.

Given you have some class, that you wanna invoke on the event

```php
class MyService {
    public function method(Consumer $consumer) {}
}
```

```yaml
services:
    # the name should be something like `rabbitmq.consumer.NAME`
    # you can make sure in source of the compiled DI Container
    name.of.the.consumer.service: 
        setup:
            - '$service->onTimeout[] = function ($consumer) { ?->method($consumer); };'(@Custom\MyService)

   - Custom\MyService
```

It should be equivalent to this

```php
$myService = new MyService;
$consumer->onTimeout[] = function ($consumer) use ($myService) { $myService->method($consumer); };
```
