### ISSUE TITLE
substr_count(): Argument #1 ($haystack) must be of type string, array given in RabbitMqExtension.php:628

### ISSUE THREAD

**Issue by topolar** [Kdyby/RabbitMq#83]
$callback->entity in fixCallback function is not string.
It's already parsed array, so substr_count throws Exception.

Steps to reproduce...
Create new Nette project, add dependencies, define rabbitmq.neon
```
rabbitmq:
    connection:
        default:
            host: 127.0.0.1
            port: 5672
            user: test
            password: test
            vhost: /
    producers:
        emails:
            exchange: {name: emails, type: direct}
    consumers:
        emails.low:
            queue: {name: emails.low, routing_keys: [emails.low]}
            exchange: {name: emails, type: direct}
            qos: {prefetchCount: 5}
            idleTimeout: 60
            callback: @App\EmailQueue::process
services:
    - App\EmailQueue()
```

Composer packages:
```
"nette/application": "^3.1",
"nette/bootstrap": "^3.1",
"nette/caching": "^3.1",
"nette/database": "^3.1",
"nette/di": "^3.0",
"nette/finder": "^2.5",
"nette/forms": "^3.1",
"nette/http": "^3.1",
"nette/mail": "^3.1",
"nette/robot-loader": "^3.3",
"nette/security": "^3.1",
"nette/utils": "^3.2",
"latte/latte": "^2.9",
"tracy/tracy": "^2.8",
"kdyby/rabbitmq": "^3.1",
"kdyby/console": "^4.0"
```
